name: deploy

on:
    push:
        branches: -main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16

            - name: Install depencies
              uses: bahmutov/npm-install@v1

            - name: Build project
              uses: npm run build

            - name: Upload built files
              uses: action/upload-artifact@v2
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{secrets.GITHUB_TOKEN}}
                  publish_dir: ./dist
